import { Module, DynamicModule, type Type } from '@nestjs/common';
import { ClientsModule } from '@nestjs/microservices';
import type { RpcClientProxy } from '../interfaces';
import { createRpcClientProxy, type RpcFunctionInfoMap } from './rpc-client';
import type { RpcCodecMetadata } from '../codecs';

/**
 * Options for RpcModule.forRoot()
 */
export interface RpcModuleOptions {
  /**
   * The ClientProxy class to use for RPC communication.
   * Typically InProcessClientProxy for monolith deployments.
   * Uses a flexible type to support both NestJS 10 (non-generic) and NestJS 11 (generic) ClientProxy.
   */
  clientProxyClass: Type<RpcClientProxy>;

  /**
   * Optional injection token for the client.
   * Defaults to 'RPC_CLIENT'.
   */
  clientToken?: string;

  /**
   * Type metadata mapping type names to their codec fields.
   * Generated by the RPC type generator (RpcTypeInfo).
   * When provided, Date fields are automatically converted.
   */
  typeInfo?: RpcCodecMetadata;

  /**
   * Function info mapping RPC patterns to their param/return type names.
   * Generated by the RPC type generator (RpcFunctionInfo).
   */
  functionInfo?: RpcFunctionInfoMap;
}

/**
 * Token used to inject the RPC ClientProxy.
 */
export const RPC_CLIENT = 'RPC_CLIENT';

/**
 * Token used to inject the configured RPC client proxy.
 * This provides a ready-to-use RPC client with automatic type transformations.
 */
export const RPC = 'RPC';

/**
 * Module that configures RPC communication for a NestJS application.
 *
 * @example
 * ```typescript
 * import { RpcModule, InProcessClientProxy } from '@zdavison/nestjs-rpc-toolkit';
 * import { RpcTypeInfo, RpcFunctionInfo } from '@your-org/lib-rpc';
 *
 * @Module({
 *   imports: [
 *     RpcModule.forRoot({
 *       clientProxyClass: InProcessClientProxy,
 *       typeInfo: RpcTypeInfo,
 *       functionInfo: RpcFunctionInfo,
 *     }),
 *   ],
 * })
 * export class AppModule {}
 *
 * // In any module, inject 'RPC' to get the configured client:
 * @Injectable()
 * class MyService {
 *   constructor(@Inject('RPC') private rpc: IRpcClient) {}
 * }
 * ```
 */
@Module({})
export class RpcModule {
  /**
   * Configure the RPC module with a specific ClientProxy implementation.
   *
   * @param options - Configuration options including the ClientProxy class
   * @returns Dynamic module configuration
   */
  static forRoot(options: RpcModuleOptions): DynamicModule {
    const clientToken = options.clientToken ?? RPC_CLIENT;

    return {
      module: RpcModule,
      imports: [
        ClientsModule.register([
          {
            name: clientToken,
            // Cast to any to support both NestJS 10 and 11 ClientProxy types
            customClass: options.clientProxyClass as any,
          },
        ]),
      ],
      providers: [
        // Provide a configured RPC client proxy with automatic type transformations
        {
          provide: RPC,
          useFactory: (client: RpcClientProxy) =>
            createRpcClientProxy(client, {
              typeInfo: options.typeInfo,
              functionInfo: options.functionInfo,
            }),
          inject: [clientToken],
        },
      ],
      exports: [ClientsModule, RPC],
      global: true,
    };
  }
}
