// Auto-generated RPC types from all modules
// Do not edit this file manually - it will be overwritten
//
// SERIALIZATION REQUIREMENTS:
// All @RpcMethod parameters and return types must be JSON-serializable for TCP transport.
// Avoid: functions, callbacks, Buffer, Map/Set, DOM elements, class instances, undefined
// Prefer: primitives, plain objects, arrays, null (instead of undefined)

import type { JsonValue } from 'type-fest';
import { UserDomain, CreateUserDto, User, LookupUsersQuery, LookupUsersResult, UserSelect, UpdateUserContactDto, UpdateUserContactResponse } from './user.rpc.gen';
import { AuthDomain, RegisterDto } from './auth.rpc.gen';
import { MessagingDomain, IncomingMessage, QueuedMessage } from './messaging.rpc.gen';
import { FormsDomain, CreateDynamicFormRequest, CreateDynamicFormResponse, FormDataRpcResponse, FormStatusResponse, SerializableObject } from './forms.rpc.gen';

// Re-export domain interfaces and types
export { UserDomain, CreateUserDto, User, LookupUsersQuery, LookupUsersResult, UserSelect, UpdateUserContactDto, UpdateUserContactResponse } from './user.rpc.gen';
export { AuthDomain, RegisterDto } from './auth.rpc.gen';
export { MessagingDomain, IncomingMessage, QueuedMessage } from './messaging.rpc.gen';
export { FormsDomain, CreateDynamicFormRequest, CreateDynamicFormResponse, FormDataRpcResponse, FormStatusResponse, SerializableObject } from './forms.rpc.gen';

// Re-export external types from their source packages
export type { JsonValue } from 'type-fest';

// Re-export common types from their primary modules


// Type mapping for RPC methods and their signatures
export type AllRpcMethods = {
  'user.create': { params: { createUserDto: CreateUserDto }; returns: User };
  'user.lookupUsers': { params: { query: LookupUsersQuery<any> }; returns: LookupUsersResult<any> };
  'user.updateContact': { params: { dto: UpdateUserContactDto }; returns: UpdateUserContactResponse };
  'auth.register': { params: { registerDto: RegisterDto }; returns: { accessToken: string; user: { id: string; email: string; }; } };
  'auth.getUserEmailsById': { params: { userIds: number[] }; returns: string[] };
  'messaging.queueMessage': { params: { message: IncomingMessage }; returns: QueuedMessage };
  'messaging.getQueueStatus': { params: {}; returns: { connected: boolean; service: string; queueLength: number; } };
  'forms.createDynamicForm': { params: { request: CreateDynamicFormRequest }; returns: CreateDynamicFormResponse };
  'forms.loadFormByToken': { params: { token: string }; returns: FormDataRpcResponse };
  'forms.checkFormStatus': { params: { token: string }; returns: FormStatusResponse };
  'forms.getFormContext': { params: { token: string }; returns: SerializableObject };
  'forms.getFormCallbackRoute': { params: { token: string }; returns: string };
  'forms.submitForm': { params: { shortCode: string; submissionData: JsonValue }; returns: void };
};


// Domain-scoped RPC client interface
export interface IRpcClient {
  user: UserDomain;
  auth: AuthDomain;
  messaging: MessagingDomain;
  forms: FormsDomain;
}

// Usage examples:
// import { TypedRpcClient } from '@modular-monolith/rpc';
//
// const user = await rpc.user.findOne({ id: 'user123' });
// const products = await rpc.product.findByOwner({ ownerId: 'user123' });
