// Auto-generated RPC types for Auth module
// Do not edit this file manually - it will be overwritten
//
// IMPORTANT: All types must be JSON-serializable for TCP transport when extracted to microservices

// Auth module types
export interface RegisterDto {
  email: string;
  password: string;
}

// Domain interface for auth module
export interface AuthDomain {
  register(params: { registerDto: RegisterDto }): Promise<{ accessToken: string; user: { id: string; email: string; }; }>;
}
