// Auto-generated RPC types for Forms module
// Do not edit this file manually - it will be overwritten
//
// IMPORTANT: All types must be JSON-serializable for TCP transport when extracted to microservices

import { JsonValue } from 'type-fest';

// Forms module types
/**
 * Field definition for forms (RPC serializable version)
 */
export interface RpcFormFieldDefinition {
  name: string;
  label: string;
  type: string;
  required: boolean | null;
  default: string | null;
  options: string[] | null;
  placeholder: string | null;
}

/**
 * RPC response for form status check
 */
export interface FormStatusResponse {
  valid: boolean;
  reason: string | null;
}

/**
 * Test case for type generation bugs (mirrors oddjob-contacts pattern):
 * 1. Type aliases should be exported
 * 2. Transitive type dependencies should be copied
 * 3. All locally-defined interfaces should be exported
 * 4. Forward-referenced types should also be included
 * 5. External types (like JsonValue from type-fest) should be re-exported correctly
 */
/**
 * JSON-like object type for RPC serialization
 */
export type SerializableObject = { [key: string]: SerializableValue };

export type SerializableValue = string | number | boolean | null | SerializableObject | SerializableValue[];

/**
 * RPC parameters for creating a dynamic form
 */
export interface CreateFormRpcParams {
  purpose: string;
  title: string;
  description: string | null;
  fields: RpcFormFieldDefinition[];
  context: SerializableObject | null;
  submitButtonText: string | null;
}

/**
 * Full RPC request for creating a dynamic form
 */
export interface CreateDynamicFormRequest {
  params: CreateFormRpcParams;
  userId: string;
  messengerAccountId: string;
}

/**
 * RPC response for form creation
 */
export interface CreateDynamicFormResponse {
  formId: string;
  schema: SerializableObject;
  createdAt: string;
}

/**
 * RPC response for form data
 */
export interface FormDataRpcResponse {
  schema: SerializableObject;
  uiSchema: SerializableObject | null;
  title: string;
  description: string | null;
  submitButtonText: string | null;
}

// Domain interface for forms module
export interface FormsDomain {
/**
   * Create a dynamic form from field definitions
   */
  createDynamicForm(params: { request: CreateDynamicFormRequest }): Promise<CreateDynamicFormResponse>;
/**
   * Load form data by token (for rendering in the web UI)
   */
  loadFormByToken(params: { token: string }): Promise<FormDataRpcResponse>;
/**
   * Check if a form is still valid (not expired or submitted)
   */
  checkFormStatus(params: { token: string }): Promise<FormStatusResponse>;
/**
   * Get the form context (for callback processing)
   */
  getFormContext(params: { token: string }): Promise<SerializableObject>;
/**
   * Get callback route for a form
   */
  getFormCallbackRoute(params: { token: string }): Promise<string>;
/**
   * Submit form data using JsonValue from type-fest (external package type).
   * This tests that external types are correctly re-exported in generated files.
   */
  submitForm(params: { shortCode: string; submissionData: JsonValue }): Promise<void>;
}
