// Auto-generated RPC types for Forms module
// Do not edit this file manually - it will be overwritten
//
// IMPORTANT: All types must be JSON-serializable for TCP transport when extracted to microservices

// Forms module types
/**
 * Test case for type generation bugs:
 * 1. Type aliases should be exported
 * 2. Transitive type dependencies should be copied
 * 3. All locally-defined interfaces should be exported
 */
export type SerializableValue = string | number | boolean | null | SerializableObject | SerializableValue[];

export type SerializableObject = { [key: string]: SerializableValue };

export interface RpcFormFieldDefinition {
  /** Name of the field */
  name: string;
  /** Display label for the field */
  label: string;
  /** Type of form field (text, number, select, etc.) */
  type: string;
  /** Whether the field is required */
  required: boolean;
  /** Default value for the field */
  defaultValue?: SerializableValue;
}

export interface CreateFormRpcParams {
  /** Purpose of the form */
  purpose: string;
  /** Field definitions for the form */
  fields: RpcFormFieldDefinition[];
  /** Optional metadata for the form */
  metadata?: SerializableObject;
}

export interface CreateDynamicFormRequest {
  /** Form creation parameters */
  params: CreateFormRpcParams;
  /** User ID creating the form */
  userId: string;
  /** Messenger account ID */
  messengerAccountId: string;
}

export interface CreateDynamicFormResponse {
  /** ID of the created form */
  formId: string;
  /** Schema of the created form */
  schema: SerializableObject;
  /** Creation timestamp */
  createdAt: string;
}

// Domain interface for forms module
export interface FormsDomain {
/**
   * Creates a dynamic form based on the provided parameters
   * @param request - The form creation request containing params, userId, and messengerAccountId
   * @returns The created form with its ID and schema
   */
  createDynamicForm(params: { request: CreateDynamicFormRequest }): Promise<CreateDynamicFormResponse>;
/**
   * Gets a form field definition by name
   * @param fieldName - The name of the field to get
   * @returns The field definition or null if not found
   */
  getFieldDefinition(params: { fieldName: string }): Promise<RpcFormFieldDefinition>;
}
