// Auto-generated RPC types for Messaging module
// Do not edit this file manually - it will be overwritten
//
// IMPORTANT: All types must be JSON-serializable for TCP transport when extracted to microservices

import type { JsonValue } from 'type-fest';

// Messaging module types
/**
 * Source of a message
 */
export enum MessageSource {
  TELEGRAM = 'telegram',
  WHATSAPP = 'whatsapp',
  SMS = 'sms',
}

export interface IncomingMessage {
  /** Unique identifier for the message */
  id: string;
  /** Source platform of the message */
  source: MessageSource;
  /** Chat ID where the message was sent */
  chatId: string;
  /** User ID who sent the message */
  userId: string;
  /** Username of the sender */
  username: string | null;
  /** Text content of the message */
  text: string;
  /** ISO 8601 timestamp when the message was received */
  timestamp: string;
  /** Additional metadata for the message */
  metadata: Record<string, string | number | boolean | null> | null;
}

export interface QueuedMessage extends IncomingMessage {
  /** ISO 8601 timestamp when the message was queued */
  queuedAt: string;
  /** Workflow ID processing this message */
  workflowId: string;
}

// Domain interface for messaging module
export interface MessagingDomain {
/**
   * Queue a message for processing
   * @param message - The incoming message to queue
   * @returns The queued message with additional metadata
   */
  queueMessage(params: { message: IncomingMessage }): Promise<QueuedMessage>;
/**
   * Get the current queue status
   * @returns Information about the message queue
   */
  getQueueStatus(params: {}): Promise<{ connected: boolean; service: string; queueLength: number; }>;
/**
   * Store arbitrary metadata with a message
   * This demonstrates external type imports (JsonValue from type-fest)
   * @param messageId - The message identifier
   * @param metadata - Arbitrary JSON-serializable metadata
   * @returns The stored metadata
   */
  storeMetadata(params: { messageId: string; metadata: JsonValue }): Promise<{ messageId: string; metadata: JsonValue; }>;
}

