// Auto-generated RPC types for User module
// Do not edit this file manually - it will be overwritten
//
// IMPORTANT: All types must be JSON-serializable for TCP transport when extracted to microservices

// User module types
export interface CreateUserDto {
  email: string;
  firstName: string;
  lastName: string;
  isActive: boolean;
}

export interface LookupUsersQuery<Select extends UserSelect = UserSelect> {
  userIds: number[];
  select: Select;
}

export interface User {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export type UserSelect = {
  id?: boolean;
  email?: boolean;
  firstName?: boolean;
  lastName?: boolean;
  isActive?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
}

// Domain interface for user module
export interface UserDomain {
  create(params: { createUserDto: CreateUserDto }): Promise<User>;
  lookupUsers<Select extends UserSelect>(params: { query: LookupUsersQuery<Select> }): Promise<Partial<User>[]>;
}
